version: '3.8'

services:
  api:
    build: .
    container_name: flymate-api
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm run start:dev

  redis:
    image: redis:6.2-alpine
    container_name: redis-server
    ports:
      - '6379:6379'
